### PR TITLE
Add support for remaining unsupported ASTC formats

### PR DESCRIPTION
**Pull request by RazielXYZ**

### CODE REVIEW

**Comment by bkaradzic** [comment]
Looks good. I'm just waiting for changes in bgfx before merging it.

**Comment by DanielGibson** [comment]
Out of interest: Where do those ASTC DDS FourCC values for width/height >= 10 come from, the ones with ':' and '<'?
The only other place where I found any ASTC DDS FourCCs is cryengine/lumberyard, and they use 'A' for 10 and 'C' for 12 (hex-style), like MAKEFOURCC('A', 'S', 'C', 'A') for ASTC_12x10: https://github.com/aws/lumberyard/blob/413ecaf24d7a534801cac64f50272fe3191d278f/dev/Code/CryEngine/CryCommon/ImageExtensionHelper.h#L1487C86-L1505

**Comment by RazielXYZ** [comment]
@DanielGibson we made them up based on the ASCII value (ie : is right after 9 in ASCII, so it would be 10, and so on)

**Comment by DanielGibson** [comment]
Thanks for the reply! :)

Are there any .dds files with ASTC data in the wild? Is there any tool that actually creates them?

**Comment by RazielXYZ** [comment]
@DanielGibson Nvidia Texture Tools can create them. It seems to use "DX10" as the fourCC for any astc format in dds, which I guess is technically correct as far as the "proper" dds spec.

**Comment by DanielGibson** [comment]
The "proper" DDS spec doesn't even mention ASTC (anymore?).

But yeah, those DXGI constants (with DX10 fourcc) seem to be more commonly supported for ASTC than the FourCCs.

**Comment by RazielXYZ** [comment]
> The "proper" DDS spec doesn't even mention ASTC (anymore?).

Yup, I don't know if it ever did.

**Comment by DanielGibson** [comment]
https://forums.developer.nvidia.com/t/nv-tt-exporter-astc-compression/122477 says regarding DXGI values 133-187 for ASTC: 

> These use the extended DXGI formats including ASTC, which take up DXGI formats 133 to 187 - you can find them listed in a few places, such as https://github.com/bkaradzic/bgfx/blob/master/src/renderer_d3d.h#L22 and https://gli.g-truc.net/0.6.1/api/a00001.html
>
> Note that these won’t be supported by all DDS readers, as they were only briefly part of the DXGI format spec (the best historical resource I have on these is that they were added to the spec by Microsoft, then removed).

And I just stumbled upon https://github.com/aws/lumberyard/blob/master/dev/Code/CryEngine/CryCommon/AzDXGIFormat.h which uses different DXGI values for ASTC (260-301 without holes instead of 133-187 with every fourth value left out) - and also defines DXGI values for ETC1/2/EAC and PVRTC, but maybe all those are freely invented and not used by anyone else, IDK

**Comment by bkaradzic** [comment]
> According to https://techarx.com/directx-12-and-direct3d-11-3-an-overview/ DX11.3 and DX12 were supposed to support ASTC, but obviously they don't

The confusion is probably because at some point D3D supported Windows Phone where these formats were beneficial. And since MSFT dropped support for Windows Phone, it became irrelevant.

**Comment by DanielGibson** [comment]
Hmm yes, that sounds plausible

**Comment by DanielGibson** [comment]
By the way (sorry for this being slightly off-topic), does anyone know of a good collection of DDS images in different encodings for testing?
I only found the ones of GLI (https://github.com/g-truc/gli/tree/master/data) but as at least some of those files are definitely defective I don't have *that* much trust in them (and having more would be better either way)

**Comment by bkaradzic** [comment]
Nope. There is issue with encoders too. Some of encoders had bugs, esp. with cubemap and texture array formats. At some point I wrote cubemap importer that worked with some ancient NVTT Photoshop plugin, but plugin didn't export correctly.

**Pull request merged**
