### PR TITLE
ASTC encoding

### PR DESCRIPTION
**Pull request by andrewwillmott**
This PR adds ASTC encoding support via -t astc4x4 etc. There's also #ifdef'd support for ASTC decoding in image.cpp, which, going by the in-file style of the existing decoders, is not really appropriate to be in the core lib, as it requires a significant amount of code from 3rdparty/astc. You might want to just exclude it, I was using it for testing, as there wasn't a clean way to inject it as part of image_decode (say).

The ASTC codec is originally from https://github.com/ARM-software/astc-encoder, I've modified it so it can be used in library form.

### CODE REVIEW

**Comment by bkaradzic** [comment]
There is some issue with VS build:
referenced in function "class vtype4<float> __cdecl eigenvector(struct mat4,float)" (?eigenvector@@YA?AV?$vtype4@M@@Umat4@@M@

**Comment by andrewwillmott** [comment]
Yup, I forgot to re-apply the usual Windows compile fixes when updating to the latest astc-encoder that's now on github. 85e79c2 fixed some of it, 3bcf40f should be the final, famous last words.

**Comment by bkaradzic** [comment]
I disabled it for now until I have time to figure out decoding and 3rdparty dependencies.

**Comment by andrewwillmott** [comment]
Thanks. I was wondering about a decoder function hook that defaulted to the checkerboard, but could be overridden by texturec.

I'll try to remember tabs v spaces next time :)

**Comment by bkaradzic** [comment]
> I'll try to remember tabs v spaces next time :)

Just install EditorConfig https://editorconfig.org/ for your favourite editor and you don't have to worry about it.

**Pull request merged**
