### PR TITLE
Fix ktx cubemap size calculation

### PR DESCRIPTION
**Pull request by goodartistscopy**
Change was introduced by commit #63 (b8a7a90)

### CODE REVIEW

**Comment by goossens** [comment]
This still doesn't work for KTX files generated with **toktx** which show the following **ktxinfo**:

> Header
> 
> identifier: «KTX 11»\r\n\x1A\n
> endianness: 0x4030201
> glType: 0x1401
> glTypeSize: 1
> glFormat: 0x1907
> glInternalformat: 0x8c41
> glBaseInternalformat: 0x1907
> pixelWidth: 1024
> pixelHeight: 1024
> pixelDepth: 0
> numberOfArrayElements: 0
> numberOfFaces: 6
> numberOfMipLevels: 1
> bytesOfKeyValueData: 28
> 
> Key/Value Data
> 
> KTXorientation: S=r,T=d
> 
> Total data size = 18874368

I did a ktxinfo on all the KTX files in bgfx/examples/runtime/textures and they are all invalid with the message:

> The KTX 1 file pHeader is invalid:
>   it describes a 3D array that is unsupported

I assume these files were created with BIMG and the issue seems to be:

> pixelDepth: 1
> numberOfArrayElements: 1

I checked some of the BGFX examples that use these invalid KTX files and they are working implying the current BIMG logic only works with invalid files.

If I comment out:

> BX_ASSERT(size == imageSize, "KTX: Image size mismatch %d (expected %d).", size, imageSize);

or change:

> const uint32_t size = mipSize * numSides;

back to the previous version of src/image.cpp, my KTX files (generated with toktx) work just fine.

Recommend undoing pull request #64 until this is sorted out. BTW: is there a way to load cubemaps in BGFX from 6 separate images instead of having to create these KTX files?

**Comment by goodartistscopy** [comment]
> Recommend undoing pull request #64 until this is sorted out. 

Agreed. I would be better to not have bimg only use numLayers > 0 for layered textures and depth > 0 for 3D textures.

> BTW: is there a way to load cubemaps in BGFX from 6 separate images instead of having to create these KTX files?

```bgfx::updateTextureCube()``` takes data face by face.

**Comment by bkaradzic** [comment]
@goossens Where did you get this ktxinfo tool?

**Comment by goodartistscopy** [comment]
@bkaradzic its one of the tool from Khronos KTX SDK https://github.com/KhronosGroup/KTX-Software

**Comment by goossens** [comment]
@bkaradzic The Khronos KTX SDK also includes the "toktx" tool that I used to create my cubemaps.

@goodartistscopy Thanks for the hint on "updateTextureCube", it works like a charm even though it appears slow. I need to figure out why.

**Pull request merged**
